com:
  company:
    other:
      name: project-test  # prueba2
      logging:
        kafka:
          uniqueTopic: a-topic #pppp
#TODO bug pending          topic: a-topic #This property disappear
          properties:
            one.other: true  #prueba
            two.seconds: "darling"


